# Generated by Django 4.2 on 2023-06-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
