# Generated by Django 4.2 on 2023-06-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
