# Generated by Django 4.2 on 2023-07-05 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
