# Generated by Django 4.2 on 2023-07-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
