# Generated by Django 4.2 on 2023-07-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='profile_pic',
        ),
    ]
